'use client'
import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@radix-ui/react-tooltip";
import { HeaderProvider } from "@/context/HeaderContext";
import { useAuthRedirect } from "@/context/useAuthRedirect";
import { ThreadProvider } from "@/context/ThreadContext";
import { ThemeProvider } from "next-themes";
import { AstProvider } from "@/context/AstContext";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useAuthRedirect();

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <HeaderProvider>
            <AstProvider>
              <ThreadProvider>
                <TooltipProvider>
                  {children}
                </TooltipProvider>
                <Toaster />
              </ThreadProvider>
            </AstProvider>
          </HeaderProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import "./globals.css";
// import { Inter } from "next/font/google";
// import { Toaster } from "@/components/ui/sonner";
// import { ThemeProvider } from "next-themes";
// import { TooltipProvider } from "@radix-ui/react-tooltip";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body>
//         {/* <ThemeProvider
//           attribute="class"
//           defaultTheme="system"
//           enableSystem
//           disableTransitionOnChange
//         > */}
//           <TooltipProvider>
//             {children}
//           </TooltipProvider>
//           <Toaster />
//         {/* </ThemeProvider> */}
//       </body>
//     </html>
//   );
// }
